ffmpeg_version: '8.1'
gpl_enabled: true
make_release: true
native_build: true
full_static: false
enable_libvmaf: true
enable_libvmaf_cuda: true
enable_libplacebo: false
disable_lv2: false
openmp: true
num_jobs: auto
async_downloads: true
download_workers: 4
macos:
  clang: macports-clang-17
linux:
  c_standard: gnu11
  cxx_standard: c++17
windows:
  backend: msys2-ucrt64
  command_mode: posix
  msys2_root: C:\msys64
  prefer_system_packages: true
